" Note: brew version of vim (compiled with python3) is required for
" jedi-vim, probably better anyways

" Automatically executes filetype plugin indent on and syntax enable
call plug#begin('~/.vim/plugged')

" fzf-vim
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
" install bat with brew for preview window highlighting

" Linting
Plug 'dense-analysis/ale'	" :ALEInfo

" Show git diffs
Plug 'airblade/vim-gitgutter'

Plug 'tomasiser/vim-code-dark'  " codedark

" Python completion
Plug 'davidhalter/jedi-vim' 	" :verbose JediDebugInfo

Plug 'tpope/vim-surround'
Plug 'tpope/vim-commentary'	" gc, gcc

" Overides any specific ftplugin indentation settings
" Run with equalprg
Plug 'editorconfig/editorconfig-vim'
Plug 'sheerun/vim-polyglot'

" Plug 'altercation/vim-colors-solarized'
" Plug 'NLKNguyen/papercolor-theme'
" Plug 'rakr/vim-one'
" Plug 'tomasr/molokai'
" Plug 'sickill/vim-monokai'
" Plug 'altercation/vim-colors-solarized'
" Plug 'morhetz/gruvbox'
" Plug 'ayu-theme/ayu-vim'
" Plug 'joshdick/onedark.vim'
call plug#end()


" THEME
colorscheme codedark


" INTERFACE
set cursorline
set rnu " relativelinenumber
set nu " show current line nu
" set laststatus=1


" SEARCH
set incsearch
set ignorecase


" COMMANDS AND BINDINGS
:command Vimrc tabe ~/.vim/vimrc
" Bind esc to jk in insert mode
inoremap jk <Esc>
" Set leader to " "?

" Allow backspace on insert mode
" https://vi.stackexchange.com/questions/2162/why-doesnt-the-backspace-key-work-in-insert-mode
set backspace=indent,eol,start


" OTHER
" Use new regular expression engine
" Fixes slow (and broken) syntax highlighting in ts files
set re=0
" git-gutter delay is governed by updatetime
set updatetime=100
