" Automatically executes filetype plugin indent on and syntax enable
call plug#begin('~/.vim/plugged')

" Theme
Plug 'arcticicestudio/nord-vim'

" fzf-vim
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'

" Linting
Plug 'dense-analysis/ale'

call plug#end()

" Theme
colorscheme nord

" Line numbers
set nu

" Bind esc to jk in insert mode
inoremap jk <Esc>

" Incremental search
set incsearch

" Case insensitive search
set ignorecase
