set nu				" line numbers
set scrolloff=5			" add margin to bottom
set hlsearch			" highlight search results
set nobackup noswapfile nowritebackup
set undodir=~/.vim/undo		" keep undo files in separate dir

syntax on			" highlighting

filetype on			" file type detection 
filetype plugin on		" load plugins for specific file types
filetype indent on		" loading the indent file for specific file types 


" PLUGINS
" Set up vim-plug if it is not installed
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Plugins will be downloaded under the specified directory.
call plug#begin('~/.vim/plugged')

Plug 'sbdchd/neoformat'

" List ends here. Plugins become visible to Vim after this call.
call plug#end()
